.PHONY: check test typecheck lint fmt format install uninstall docs

# Install the `seba` CLI globally and link the seba-tutor skill into Claude Code.
install:
	./scripts/install.sh

# Remove both.
uninstall:
	./scripts/uninstall.sh

# Run every CI check locally.
check: lint fmt typecheck test

test:
	uv run pytest -q

typecheck:
	uv run ty check src

lint:
	uv run ruff check .

# CI gate: fails if anything is unformatted.
fmt:
	uv run ruff format --check .

# Dev convenience: apply formatting in place.
format:
	uv run ruff format .

# Regenerate the CLI reference from the code. `tests/test_cli_docs.py` fails
# CI if docs/cli.md drifts from this output.
docs:
	@tmp=$$(mktemp); \
	uv run typer seba.cli utils docs --name seba --output $$tmp; \
	{ printf '%s\n\n' '<!-- Generated by `make docs` from `src/seba/cli.py`. Do not edit by hand. -->'; cat $$tmp; } > docs/cli.md; \
	rm -f $$tmp
