import subprocess
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).parents[1]
DOCS_HEADER = (
    "<!-- Generated by `make docs` from `src/seba/cli.py`. Do not edit by hand. -->\n\n"
)


def test_cli_md_matches_generated_output():
    """`docs/cli.md` must be the byte-identical output of `make docs`."""
    with tempfile.NamedTemporaryFile(suffix=".md") as tmp:
        subprocess.run(
            [
                "uv",
                "run",
                "typer",
                "seba.cli",
                "utils",
                "docs",
                "--name",
                "seba",
                "--output",
                tmp.name,
            ],
            cwd=REPO_ROOT,
            check=True,
            capture_output=True,
        )
        body = Path(tmp.name).read_text()

    expected = DOCS_HEADER + body
    actual = (REPO_ROOT / "docs" / "cli.md").read_text()
    assert actual == expected, (
        "docs/cli.md is stale; run `make docs` and commit the result."
    )
