#!/usr/bin/env bash
# Generate or check docs/cli.md, the CLI reference generated from src/seba/cli.py.
# Usage: scripts/check-doc-gen.sh gen | scripts/check-doc-gen.sh check
set -euo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo"

header='<!-- Generated by `make docs-gen` from `src/seba/cli.py`. Do not edit by hand. -->'
out="docs/cli.md"

gen() {
  tmp=$(mktemp)
  uv run typer seba.cli utils docs --name seba --output "$tmp"
  { printf '%s\n\n' "$header"; cat "$tmp"; } > "$out"
  rm -f "$tmp"
}

check() {
  gen
  if ! git ls-files --error-unmatch "$out" > /dev/null 2>&1; then
    echo "$out is not tracked by git; run 'make docs-gen' and commit it."
    exit 1
  fi
  if ! git diff --exit-code -- "$out"; then
    echo "$out is stale; run 'make docs-gen' and commit the result."
    exit 1
  fi
}

case "${1:-}" in
  gen) gen ;;
  check) check ;;
  *)
    echo "usage: $0 gen|check" >&2
    exit 1
    ;;
esac
